### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (912,1581,3) (960,1664,3)

### ISSUE THREAD

**Issue by zihualiu1997** [TheMistoAI/ComfyUI-Anyline#13]
![image](https://github.com/TheMistoAI/ComfyUI-Anyline/assets/144887244/26dc4f10-e8b5-46dc-839c-a1999c92bc1b)
when I use this preprocessor for one 1632*912 image, it will cause this error, but if I change the resolution to1632*960 or 1632*1024, this preprocessor work good.
Does this processor have any limitations on image size? Or maybe I'm just overlooking some common sense.

**Comment by baizh0u** [comment]
try to uncheck perfect-pixel on yuor webui interface and try again. It should works.

**Comment by zihualiu1997** [comment]
> try to uncheck perfect-pixel on your webui interface and try again. It should works.

thanks a lot! it works!
