### ISSUE TITLE
Why ControlNet Aux?

### ISSUE THREAD

**Issue by Lalimec** [TheMistoAI/ComfyUI-Anyline#14]
Is there a reason this preprocessor requires cn Aux? I ve been using the ComfyUI-Inference-Core-Nodes ones and dont want to cause conflict again.

**Comment by xyhStruggler** [comment]
> Is there a reason this preprocessor requires cn Aux? I ve been using the ComfyUI-Inference-Core-Nodes ones and dont want to cause conflict again.

We used these four comfyui_controlnet_aux funcsions and classes below:
from custom_nodes.comfyui_controlnet_aux.utils import common_annotator_call
from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed import TEDDetector
from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed.ted import TED
from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.lineart_standard import LineartStandardDetector

If ComfyUI-Inference-Core-Nodes also contains those wheels, feel free to change the code in anyline.py and try it.
