### ISSUE TITLE
Does this node currently support batch operations? I encountered this problem while batch processing images: "ValueError: operands could not be broadcast together with shapes (21,1280,3,3) (21,1280,2276,3)"

### ISSUE THREAD

**Issue by zwbpds** [TheMistoAI/ComfyUI-Anyline#15]
Does this node currently support batch operations? I encountered this problem while batch processing images: "ValueError: operands could not be broadcast together with shapes (21,1280,3,3) (21,1280,2276,3)"
![微信截图_20240608021213](https://github.com/TheMistoAI/ComfyUI-Anyline/assets/129570694/18a5d477-dcee-45ea-af9a-8a1bcc27813d)

**Comment by xyhStruggler** [comment]
https://github.com/TheMistoAI/ComfyUI-Anyline/issues/4#issuecomment-2120808241 #4

**Comment by zwbpds** [comment]
Okay, I solved this problem. Currently anyline does not support batch processing, but manually adding a batch node can indeed solve this problem. Thanks to the author for his previous answer.
![Uploading 微信截图_20240611220410.jpg…]()
