### ISSUE TITLE
Model not found locally, downloading from HuggingFace...

### ISSUE THREAD

**Issue by BuffMcBigHuge** [TheMistoAI/ComfyUI-Anyline#2]
There seems to be a bug where it will redownload the model "MTEED.pth" everytime it runs. I think it's because there is a directory added in the checkpoints folder.

**Comment by xyhStruggler** [comment]
It will check if you have MTEED.pth under ComfyUI-Anyline
/checkpoints/ dir. Could you check if you have that model already?

**Comment by zixuzhuang** [comment]
Your MTEED.pth only have 273kb, why not add it to github files?

**Comment by daqingliu** [comment]
even though there is the file, the plugin will still redownload it ...

**Comment by xyhStruggler** [comment]
> even though there is the file, the plugin will still redownload it ...

I've put the model under the correct directory. Try pull or redownload the repo again and see if the problem still exists.
