### ISSUE TITLE
May I ask if the red circle on this node requires any input information?

### ISSUE THREAD

**Issue by qingdengke88** [TheMistoAI/ComfyUI-Anyline#5]
<img width="767" alt="微信图片_20240519100716" src="https://github.com/TheMistoAI/ComfyUI-Anyline/assets/169616938/fe0d3af2-0fcf-49a3-9caa-f1d5877aa108">
May I ask if the red circle on this node requires any input information? Why do I get stuck at this node when I run? There was no error message either？

**Comment by baizh0u** [comment]
It is a extra-plugin, just remove it and use the original node from ComfyUI...

**Comment by baizh0u** [comment]
It is a extra-plugin, just remove it and use the original node from ComfyUI...
