### ISSUE TITLE
What is the ComfyUI theme in the README image?

### ISSUE THREAD

**Issue by oxysoft** [TheMistoAI/ComfyUI-Anyline#7]
In the README you have this image

![](https://github.com/TheMistoAI/ComfyUI-Anyline/blob/main/examples/Anyline+MistoLine_workflow.jpg?raw=true)

I'm just wondering where we can find this theme? I think it looks great and very clean!

**Comment by xyhStruggler** [comment]
That's the default theme lol. Maybe it just looks better in the screenshot.

**Comment by oxysoft** [comment]
Ahhh just found it. It's not the default but it is one of the defaults, it's the 'Github' color palette. A while back there were only Dark and Light, seems we got more options now.
