### ISSUE TITLE
Could you please provide the original image? It will be used for verification purposes only.

### ISSUE THREAD

**Issue by Whoo-jl** [TheMistoAI/ComfyUI-Anyline#9]
Could you please provide the original image? It will be used for verification purposes only.
![intro](https://github.com/TheMistoAI/ComfyUI-Anyline/assets/52949064/e42a6a18-4320-48e4-bdb8-73b33263309c)

**Comment by xyhStruggler** [comment]
We open-sourced this line preprocessor only to provide convenient usage for SDXL users. You can use your own image to verify it's result.
